"""Generate TypeScript declarations and a bounded validator from FastAPI OpenAPI.

No application workspace is opened: OpenAPI construction uses a temporary home.
Only JSON responses participate; file downloads keep their existing integrity
checks. --check compares exact generated bytes and never rewrites artifacts.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from paper_alpha.server.api import create_app


# Refuse new constraint vocabulary until both TS/runtime projections implement it.
SUPPORTED_KEYS = {'$ref', 'type', 'const', 'enum', 'anyOf', 'oneOf', 'allOf',
                  'properties', 'required', 'additionalProperties', 'items',
                  'minLength', 'maxLength', 'pattern', 'minimum', 'maximum',
                  'exclusiveMinimum', 'exclusiveMaximum', 'minItems', 'maxItems',
                  'title', 'description', 'default', 'contentMediaType', 'discriminator'}


def validate_vocabulary(schema):
    unsupported = set(schema) - SUPPORTED_KEYS
    if unsupported:
        raise ValueError('Unsupported API schema keywords: ' + ', '.join(sorted(unsupported)))
    if 'type' in schema and (not isinstance(schema['type'], str) or schema['type'] not in {'string', 'integer', 'number', 'boolean', 'null', 'array', 'object'}):
        raise ValueError('Unsupported API schema type')
    if 'discriminator' in schema:
        discriminator = schema['discriminator']
        choices = {part.get('$ref') for part in schema.get('oneOf', [])}
        if (not isinstance(discriminator, dict) or set(discriminator) != {'propertyName', 'mapping'}
                or not isinstance(discriminator['propertyName'], str) or not discriminator['propertyName']
                or not isinstance(discriminator['mapping'], dict) or not discriminator['mapping']
                or any(not isinstance(key, str) or not isinstance(value, str)
                       for key, value in discriminator['mapping'].items())
                or None in choices or set(discriminator['mapping'].values()) != choices):
            raise ValueError('Unsupported API discriminator; expected a closed oneOf reference mapping')
    for value in schema.get('properties', {}).values():
        validate_vocabulary(value)
    for key in ('items', 'additionalProperties'):
        if isinstance(schema.get(key), dict):
            validate_vocabulary(schema[key])
    for key in ('anyOf', 'oneOf', 'allOf'):
        for value in schema.get(key, []):
            validate_vocabulary(value)


def ts(schema):
    if not schema:
        return 'unknown'
    if '$ref' in schema:
        return schema['$ref'].rsplit('/', 1)[-1]
    if 'const' in schema:
        return json.dumps(schema['const'])
    if 'enum' in schema:
        return ' | '.join(json.dumps(value) for value in schema['enum'])
    for key, join in (('anyOf', ' | '), ('oneOf', ' | '), ('allOf', ' & ')):
        if key in schema:
            return '(' + join.join(ts(part) for part in schema[key]) + ')'
    kind = schema.get('type')
    if kind == 'array':
        return 'Array<' + ts(schema.get('items', {})) + '>'
    if kind == 'object':
        properties = schema.get('properties', {})
        required = schema.get('required', [])
        fields = [json.dumps(key) + ('' if key in required else '?') + ': ' + ts(value) + ';' for key, value in properties.items()]
        extra = schema.get('additionalProperties', True)
        if extra is not False:
            fields.append('[key: string]: ' + (ts(extra) if isinstance(extra, dict) else 'unknown') + ';')
        return '{ ' + ' '.join(fields) + ' }'
    return {'string': 'string', 'integer': 'number', 'number': 'number', 'boolean': 'boolean', 'null': 'null'}.get(kind, 'unknown')


RUNTIME = r'''
// This deliberately implements only the emitted OpenAPI schema vocabulary.
// It validates shape, required/null fields, literals/enums and finite JSON types;
// scientific semantics and input validation remain owned by the server.
type Schema = { [key: string]: unknown; $ref?: string; type?: string; const?: unknown; enum?: unknown[];
  anyOf?: Schema[]; oneOf?: Schema[]; allOf?: Schema[];
  discriminator?: { propertyName: string; mapping: Record<string, string> };
  properties?: Record<string, Schema>; required?: string[];
  additionalProperties?: boolean | Schema; items?: Schema;
  minLength?: number; maxLength?: number; pattern?: string;
  minimum?: number; maximum?: number; exclusiveMinimum?: number; exclusiveMaximum?: number;
  minItems?: number; maxItems?: number };
type Route = { method: string; path: string; responses: Record<string, Schema> };
const schemaLookup: Record<string, Schema> = contractSchemas;
const routes: Route[] = contractRoutes;

export class ApiContractError extends Error {
  constructor(readonly location: string) {
    super(`服务响应与接口契约不一致（${location}），请保留当前输入并检查服务版本。`);
    this.name = 'ApiContractError';
  }
}
function validate(schema: Schema, value: unknown, location: string, depth = 0): void {
  if (depth > 100) throw new ApiContractError(location + ': maximum nesting exceeded');
  if (schema.$ref) {
    const target = schemaLookup[schema.$ref.split('/').at(-1)!];
    if (!target) throw new ApiContractError(location + ': unknown schema');
    return validate(target, value, location, depth + 1);
  }
  if (schema.discriminator) {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) throw new ApiContractError(location);
    const discriminator = (value as Record<string, unknown>)[schema.discriminator.propertyName];
    if (typeof discriminator !== 'string' || !Object.prototype.hasOwnProperty.call(schema.discriminator.mapping, discriminator)) throw new ApiContractError(location);
  }
  const alternatives = schema.anyOf ?? schema.oneOf;
  if (alternatives) {
    let matched = 0;
    for (const option of alternatives) {
      try { validate(option, value, location, depth + 1); matched++; if (!schema.oneOf) return; }
      catch (error) { if (!(error instanceof ApiContractError)) throw error; }
    }
    if (schema.oneOf && matched === 1) return;
    throw new ApiContractError(location);
  }
  if (schema.allOf) for (const item of schema.allOf) validate(item, value, location, depth + 1);
  if (Object.prototype.hasOwnProperty.call(schema, 'const') && value !== schema.const) throw new ApiContractError(location);
  if (schema.enum && !schema.enum.includes(value)) throw new ApiContractError(location);
  if (schema.type === 'null' && value !== null) throw new ApiContractError(location);
  if (schema.type === 'boolean' && typeof value !== 'boolean') throw new ApiContractError(location);
  if (schema.type === 'string') {
    if (typeof value !== 'string' || (schema.minLength !== undefined && [...value].length < schema.minLength)
        || (schema.maxLength !== undefined && [...value].length > schema.maxLength)
        || (schema.pattern !== undefined && !new RegExp(schema.pattern).test(value))) throw new ApiContractError(location);
  }
  if (schema.type === 'number' || schema.type === 'integer') {
    if (typeof value !== 'number' || !Number.isFinite(value)
        || (schema.type === 'integer' && !Number.isInteger(value))
        || (schema.minimum !== undefined && value < schema.minimum)
        || (schema.maximum !== undefined && value > schema.maximum)
        || (schema.exclusiveMinimum !== undefined && value <= schema.exclusiveMinimum)
        || (schema.exclusiveMaximum !== undefined && value >= schema.exclusiveMaximum)) throw new ApiContractError(location);
  }
  if (schema.type === 'array') {
    if (!Array.isArray(value) || (schema.minItems !== undefined && value.length < schema.minItems)
        || (schema.maxItems !== undefined && value.length > schema.maxItems)) throw new ApiContractError(location);
    for (let i = 0; i < value.length; i++) validate(schema.items ?? {}, value[i], `${location}[${i}]`, depth + 1);
  }
  if (schema.type === 'object') {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) throw new ApiContractError(location);
    const object = value as Record<string, unknown>;
    const properties = schema.properties ?? {};
    for (const key of schema.required ?? []) {
      if (!Object.prototype.hasOwnProperty.call(object, key)) throw new ApiContractError(location + '.' + key);
    }
    for (const [key, item] of Object.entries(object)) {
      if (Object.prototype.hasOwnProperty.call(properties, key)) validate(properties[key], item, location + '.' + key, depth + 1);
      else if (schema.additionalProperties === false) throw new ApiContractError(location + '.' + key);
      else if (typeof schema.additionalProperties === 'object') validate(schema.additionalProperties, item, location + '.' + key, depth + 1);
    }
  }
}
function matches(template: string, path: string): boolean {
  const actual = path.split('/'), expected = template.split('/');
  return actual.length === expected.length && expected.every((part, i) =>
    part.startsWith('{') ? actual[i].length > 0 : part === actual[i]);
}
export function assertApiResponse(path: string, method: string, status: number, data: unknown): void {
  const pathname = path.split('?')[0];
  const route = routes.find((item) => item.method === method.toUpperCase() && matches(item.path, pathname));
  if (!route) throw new ApiContractError(`${method.toUpperCase()} ${pathname}: undocumented route`);
  const schema = route.responses[String(status)] ?? route.responses.default;
  if (!schema) throw new ApiContractError(`${method.toUpperCase()} ${pathname}: undocumented status ${status}`);
  validate(schema, data, `${method.toUpperCase()} ${pathname} ${status}`);
}
'''


def generate():
    with tempfile.TemporaryDirectory(prefix='paper-alpha-openapi-') as home:
        document = create_app(Path(home)).openapi()
    schemas = document['components']['schemas']
    for schema in schemas.values():
        validate_vocabulary(schema)
    routes = []
    for path, methods in sorted(document['paths'].items()):
        for method, operation in sorted(methods.items()):
            responses = {code: item['content']['application/json']['schema']
                         for code, item in operation.get('responses', {}).items()
                         if 'application/json' in item.get('content', {})
                         and item['content']['application/json'].get('schema')}
            # Binary/text downloads are not passed through the JSON API helper.
            if not any(code.startswith('2') for code in responses):
                continue
            routes.append({'method': method.upper(), 'path': path, 'responses': responses})
    banner = '// Generated by scripts/export_api_contract.py; do not edit.\n'
    declarations = '\n'.join('export type ' + name + ' = ' + ts(schema) + ';' for name, schema in sorted(schemas.items()))
    # Pydantic qualifies equal class names from distinct scopes. Preserve the
    # original frontend type through its exact original response contract.
    if 'AssessmentDimensions' not in schemas and 'ResearchAssessment' in schemas:
        declarations += '\nexport type AssessmentDimensions = ResearchAssessment["dimensions"];'
    compact = lambda value: json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(',', ':'))
    source = (banner + declarations + '\n\nexport const contractSchemas: Record<string, Schema> = ' + compact(schemas)
              + ';\nexport const contractRoutes: Route[] = ' + compact(routes) + ';\n' + RUNTIME)
    contract = {'openapi': document['openapi'], 'info': document['info'], 'paths': document['paths'], 'components': document['components']}
    return {'api-contract.ts': source,
            'openapi.json': json.dumps(contract, ensure_ascii=False, sort_keys=True, indent=2) + '\n'}


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--out', type=Path, default=ROOT / 'frontend/src/generated')
    args = parser.parse_args(argv)
    outputs = generate()
    drift = []
    for name, content in outputs.items():
        target = args.out / name
        if args.check:
            if not target.is_file() or target.read_text() != content:
                drift.append(name)
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content)
    if drift:
        print('API contract drift: ' + ', '.join(drift) + '; run scripts/export_api_contract.py', file=sys.stderr)
        return 1
    print(('Verified' if args.check else 'Generated') + ' API contract: ' + ', '.join(outputs))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
